apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
      protocol: TCP
    - port: 50000
      targetPort: 50000
      nodePort: 30011
      protocol: TCP
  selector:
    app: jenkins
