version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-tst-net
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data:

networks:
  jenkins-tst-net:
    external: true
